### PR TITLE
Add DISCLAIMER to jars

### PR DESCRIPTION
**Pull request by zhoujinsong**
As titled.

### CODE REVIEW

**Comment by pjfanning** [comment]
can this be added in time for the next RC?

**Comment by zhoujinsong** [comment]
> can this be added in time for the next RC?

Amoro-shade 0.7.0-incubating has been released, we may add this in the next release.

**Review by zhongqishang — APPROVED** [review]
LGTM.

**Comment by zhongqishang** [comment]
./amoro-shade/amoro-shade-guava-32/target/META-INF
```
% cat DISCLAIMER 
amoro-shade-guava-32 is an effort undergoing incubation at the Apache Software 
Foundation (ASF), sponsored by the Apache Incubator PMC. 

Incubation is required of all newly accepted projects until a further review 
indicates that the infrastructure, communications, and decision making process 
have stabilized in a manner consistent with other successful ASF projects. 

While incubation status is not necessarily a reflection of the completeness 
or stability of the code, it does indicate that the project has yet to be 
fully endorsed by the ASF.
```

**Pull request merged**
